spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: root
   url: jdbc:mysql://localhost:3306/campus_trade?useUnicode=true&characterEncoding=utf8
server:
  port: 8080
mybatisplus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
custom:
  avatar:
    upload-dir: D:/毕业设计/李文栋/upload/avatars  # 默认用户目录下的uploads/avatars
    access-path: /avatars/**                   # 对外访问路径
  redis:
    host: localhost
    port: 6379
    database: 0
    # password: your_redis_password    # 如有密码则取消注释
    timeout: 3000ms